version: "3"

services:
  jupyter:
    image: tensorflow/tensorflow:2.9.0rc2-gpu-jupyter
    volumes:
      - ./src:/tf
      - ./data:/tf/data
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]